name: Trigger SciTechNow AWS CodePipeline

on:
  push:
    branches:
    - 'dev'
    - 'preprod'
    - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger SciTechNow DEV AWS CodePipeline
        uses: zulhfreelancer/aws-codepipeline-action@v1.0.7
        if: github.ref == 'refs/heads/dev'
        with:
          aws-region: "us-east-1"
          aws-access-key: ${{ secrets.DEV_AWS_CODEPIPELINE_ACCESS_KEY }}
          aws-secret-key: ${{ secrets.DEV_AWS_CODEPIPELINE_SECRET_KEY }}
          pipeline-name: "scitechnow"
      - name: Trigger SciTechNow PREPROD AWS CodePipeline
        uses: zulhfreelancer/aws-codepipeline-action@v1.0.7
        if: github.ref == 'refs/heads/preprod'
        with:
          aws-region: "us-east-1"
          aws-access-key: ${{ secrets.PREPROD_AWS_CODEPIPELINE_ACCESS_KEY }}
          aws-secret-key: ${{ secrets.PREPROD_AWS_CODEPIPELINE_SECRET_KEY }}
          pipeline-name: "scitechnow"
      - name: Trigger SciTechNow PROD AWS CodePipeline
        uses: zulhfreelancer/aws-codepipeline-action@v1.0.7
        if: github.ref == 'refs/heads/main'
        with:
          aws-region: "us-east-1"
          aws-access-key: ${{ secrets.PROD_AWS_CODEPIPELINE_ACCESS_KEY }}
          aws-secret-key: ${{ secrets.PROD_AWS_CODEPIPELINE_SECRET_KEY }}
          pipeline-name: "scitechnow"